# Test workflow- runs on all PR's.
name: Test

on:
  pull_request:
    branches:
      - staging
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Checkout from GitHub
      - name: Checkout code
        uses: actions/checkout@v1
      # Set up Node
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      # jest tests
      - run: npm install
      - run: npm test
      # cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        env:
          # Don't leak those secrets!
          SCRATCH_USERNAME: ${{ secrets.SCRATCH_USERNAME }}
          SCRATCH_PASSWORD: ${{ secrets.SCRATCH_PASSWORD }}
        with:
          build: npm run build
          start: npm start
          wait-on: http://localhost:3000
          browser: chrome
